version: '3'

services:
  local:
    container_name: dispshell
    build:
      context: .
      dockerfile: dispshell.Dockerfile
    tty: true
    volumes:
      - ./local:/root/local
  mine:
    container_name: dispshell-mine
    build:
      context: .
      dockerfile: dispshell-mine.Dockerfile
      args:
        USERNAME: ${USERNAME}
    tty: true
  sshd:
    container_name: dispshell-sshd
    build:
      context: .
      dockerfile: dispshell-sshd.Dockerfile
      args:
        USERNAME: ${USERNAME}
    tty: true
    ports:
      - "10022:22"